[pytest]
DJANGO_SETTINGS_MODULE = testmanager.settings
asyncio_default_fixture_loop_scope = function
python_files = tests.py test_*.py *_tests.py
addopts = --cov=. --cov-report=html --cov-report=term --cov-fail-under=60 --create-db
filterwarnings =
    ignore::pytest.PytestUnhandledThreadExceptionWarning
    ignore::DeprecationWarning