# Generated by Django 5.2.6 on 2026-04-09 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("functional", "功能测试"),
                            ("api", "API测试"),
                            ("ui", "UI测试"),
                            ("flow", "流程测试"),
                        ],
                        default="functional",
                        max_length=20,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("blocked", "阻塞"),
                            ("skipped", "跳过"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="执行时间",
                    ),
                ),
                ("duration", models.FloatField(default=0, verbose_name="执行时长(秒)")),
                (
                    "actual_result",
                    models.TextField(blank=True, verbose_name="实际结果"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "api_response_data",
                    models.JSONField(blank=True, null=True, verbose_name="API响应数据"),
                ),
                ("api_logs", models.TextField(blank=True, verbose_name="API执行日志")),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="截图路径"
                    ),
                ),
                (
                    "log_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="日志文件路径"
                    ),
                ),
            ],
            options={
                "verbose_name": "测试执行记录",
                "verbose_name_plural": "测试执行记录",
                "db_table": "core_test_execution",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="TestFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Flow Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "scenario_description",
                    models.TextField(verbose_name="Scenario Description"),
                ),
                ("flow_data", models.JSONField(default=dict, verbose_name="Flow Data")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Test Flow",
                "verbose_name_plural": "Test Flows",
                "db_table": "core_test_flow",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TestFlowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_data",
                    models.JSONField(default=dict, verbose_name="Execution Data"),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Execution Result"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Execution Metrics"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Flow Execution",
                "verbose_name_plural": "Flow Executions",
                "db_table": "core_test_flow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Knowledge Base Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="sentence-transformers/all-MiniLM-L6-v2",
                        max_length=255,
                        verbose_name="Embedding Model",
                    ),
                ),
                (
                    "chunk_size",
                    models.IntegerField(default=1000, verbose_name="Chunk Size"),
                ),
                (
                    "chunk_overlap",
                    models.IntegerField(default=200, verbose_name="Chunk Overlap"),
                ),
                (
                    "document_count",
                    models.IntegerField(default=0, verbose_name="Document Count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_knowledge_bases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base",
                "verbose_name_plural": "Knowledge Bases",
                "db_table": "core_knowledge_base",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("prd", "PRD文档"),
                            ("api_doc", "接口文档"),
                            ("feature_test", "功能测试用例"),
                            ("api_test", "接口测试用例"),
                            ("ui_test", "UI用例"),
                        ],
                        max_length=50,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="File Path"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Vector Embedding"
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(default=0, verbose_name="Chunk Index"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "chroma_id_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Format: doc_{id}_, for batch deletion of all chunks",
                        max_length=50,
                        null=True,
                        verbose_name="ChromaDB Document ID Prefix",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Sync Status",
                    ),
                ),
                ("sync_error", models.TextField(blank=True, verbose_name="Sync Error")),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Synced At"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_knowledge_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.knowledgebase",
                        verbose_name="Knowledge Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
                "db_table": "core_knowledge_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Project Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Project Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "core_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Module Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Module Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_modules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "core_module",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_bases",
                to="core.project",
                verbose_name="Project",
            ),
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("ui_test", "UI Test Agent"),
                            ("api_test", "API Test Agent"),
                            ("test_generation", "Test Generation Agent"),
                            ("code_generation", "Code Generation Agent"),
                            ("error_analysis", "Error Analysis Agent"),
                            ("test_planning", "Test Planning Agent"),
                            ("knowledge_retrieval", "Knowledge Retrieval Agent"),
                        ],
                        max_length=50,
                        verbose_name="Agent Type",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("test_planning", "Test Planning"),
                            ("code_generation", "Code Generation"),
                            ("test_execution", "Test Execution"),
                            ("knowledge_retrieval", "Knowledge Retrieval"),
                            ("error_analysis", "Error Analysis"),
                            ("flow_generation", "Flow Generation"),
                        ],
                        max_length=50,
                        verbose_name="Task Type",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Execution ID"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, verbose_name="Input Data"),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Output Data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="Metrics"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_executions",
                        to="core.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Execution",
                "verbose_name_plural": "Agent Executions",
                "db_table": "core_agent_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("ui_test", "UI Test Agent"),
                            ("api_test", "API Test Agent"),
                            ("test_generation", "Test Generation Agent"),
                            ("code_generation", "Code Generation Agent"),
                            ("error_analysis", "Error Analysis Agent"),
                            ("test_planning", "Test Planning Agent"),
                            ("knowledge_retrieval", "Knowledge Retrieval Agent"),
                        ],
                        max_length=50,
                        verbose_name="Agent Type",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Conversation ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "intent_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Intent Type"
                    ),
                ),
                ("messages", models.JSONField(default=list, verbose_name="Messages")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "migrated_to_markdown",
                    models.BooleanField(
                        default=False, verbose_name="Migrated to Markdown"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversations",
                        to="core.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Conversation",
                "verbose_name_plural": "Agent Conversations",
                "db_table": "core_agent_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="用例标题")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "紧急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                ("steps", models.TextField(verbose_name="测试步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testcases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="core.module",
                        verbose_name="所属模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "db_table": "core_test_case",
                "ordering": ["-created_at"],
            },
        ),
    ]
