# Generated by Django 5.2.6 on 2026-04-09 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("testmanager_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="api_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="testmanager_app.apirequest",
                verbose_name="API请求",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="collection_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_executions",
                to="testmanager_app.collectionexecution",
                verbose_name="所属集合执行",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="executed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="执行人",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="test_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.testcase",
                verbose_name="功能测试用例",
            ),
        ),
        migrations.AddField(
            model_name="testflow",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_flows",
                to="core.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="testflow",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_test_flows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="testflowexecution",
            name="test_flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.testflow",
                verbose_name="Test Flow",
            ),
        ),
        migrations.AddField(
            model_name="testflowexecution",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_flow_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executed By",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["knowledge_base", "document_type"],
                name="core_knowle_knowled_525ced_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["sync_status"], name="core_knowle_sync_st_055687_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["agent_type", "task_type"],
                name="core_agent__agent_t_203486_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["project", "status"], name="core_agent__project_c1af37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["user", "created_at"], name="core_agent__user_id_2a4369_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentconversation",
            index=models.Index(
                fields=["agent_type", "project"], name="core_agent__agent_t_b69cdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentconversation",
            index=models.Index(
                fields=["user", "created_at"], name="core_agent__user_id_ca70ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testflow",
            index=models.Index(
                fields=["project", "is_active"], name="core_test_f_project_4fa774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testflow",
            index=models.Index(fields=["user"], name="core_test_f_user_id_31bede_idx"),
        ),
        migrations.AddIndex(
            model_name="testflowexecution",
            index=models.Index(
                fields=["test_flow", "status"], name="core_test_f_test_fl_ef12ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testflowexecution",
            index=models.Index(
                fields=["user", "created_at"], name="core_test_f_user_id_8a1fd5_idx"
            ),
        ),
    ]
