# Generated by Django 5.2.6 on 2026-04-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBotExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(db_index=True, max_length=64)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("skill", "Skill执行"),
                            ("api_test", "接口测试"),
                            ("ui_test", "UI测试"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_logs",
                        to="core.testexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "ChatBot执行日志",
                "verbose_name_plural": "ChatBot执行日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id", "-created_at"],
                        name="core_chatbo_convers_c15ef2_idx",
                    ),
                    models.Index(
                        fields=["log_type", "-created_at"],
                        name="core_chatbo_log_typ_f6df9d_idx",
                    ),
                ],
            },
        ),
    ]
