# Generated by Django 5.2.6 on 2026-04-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_chatbotexecutionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testexecution",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("functional", "功能测试"),
                    ("api", "API测试"),
                    ("flow", "流程测试"),
                ],
                default="functional",
                max_length=20,
                verbose_name="测试类型",
            ),
        ),
    ]
