# Generated by Django 5.2.6 on 2026-04-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_remove_ui_from_test_type_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="脚本名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "script_type",
                    models.CharField(
                        choices=[
                            ("api", "API测试"),
                            ("ui", "UI测试"),
                            ("pressure", "压测"),
                            ("advanced_pressure", "高级压测"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="脚本类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="源模型ID")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="源模型类型",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_scripts",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "统一脚本",
                "verbose_name_plural": "统一脚本",
                "db_table": "core_unified_script",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("stopped", "已停止"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="源模型ID")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="源模型类型",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "unified_script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.unifiedscript",
                        verbose_name="统一脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "统一执行记录",
                "verbose_name_plural": "统一执行记录",
                "db_table": "core_unified_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="unifiedscript",
            index=models.Index(
                fields=["script_type", "is_active"],
                name="core_unifie_script__68e898_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedscript",
            index=models.Index(
                fields=["project", "script_type"], name="core_unifie_project_15cef4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unifiedscript",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"),
                name="unique_unified_script_source",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedexecution",
            index=models.Index(
                fields=["unified_script", "status"],
                name="core_unifie_unified_b3639f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedexecution",
            index=models.Index(
                fields=["executed_by", "started_at"],
                name="core_unifie_execute_ea91cb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="unifiedexecution",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"),
                name="unique_unified_execution_source",
            ),
        ),
    ]
