# Generated by Django 5.2.6 on 2026-04-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_unifiedscript_unifiedexecution_and_more"),
        ("testmanager_app", "0005_add_is_critical_to_apiassertion"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="错误信息"),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="step_results",
            field=models.JSONField(
                blank=True,
                help_text='格式: {"total": 10, "passed": 8, "failed": 2, "details": [...]}',
                null=True,
                verbose_name="步骤执行结果",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="test_script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="testmanager_app.testscript",
                verbose_name="测试脚本",
            ),
        ),
        migrations.AlterField(
            model_name="testexecution",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("functional", "功能测试"),
                    ("api", "API测试"),
                    ("flow", "流程测试"),
                    ("script", "测试脚本"),
                ],
                default="functional",
                max_length=20,
                verbose_name="测试类型",
            ),
        ),
    ]
