# Generated by Django 5.2.6 on 2026-04-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_script_fields_to_test_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="unifiedexecution",
            name="logs",
            field=models.TextField(blank=True, verbose_name="执行日志"),
        ),
        migrations.AddField(
            model_name="unifiedexecution",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unified_executions",
                to="core.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="unifiedexecution",
            name="script_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="脚本/配置名称"
            ),
        ),
        migrations.AddField(
            model_name="unifiedexecution",
            name="script_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("api", "API测试"),
                    ("ui", "UI测试"),
                    ("pressure", "压测"),
                    ("advanced_pressure", "高级压测"),
                    ("script", "测试脚本"),
                    ("chatbot", "ChatBot执行"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="脚本类型",
            ),
        ),
        migrations.AlterField(
            model_name="unifiedexecution",
            name="unified_script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.unifiedscript",
                verbose_name="统一脚本",
            ),
        ),
        migrations.AlterField(
            model_name="unifiedscript",
            name="script_type",
            field=models.CharField(
                choices=[
                    ("api", "API测试"),
                    ("ui", "UI测试"),
                    ("pressure", "压测"),
                    ("advanced_pressure", "高级压测"),
                    ("script", "测试脚本"),
                    ("chatbot", "ChatBot执行"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="脚本类型",
            ),
        ),
    ]
