# Generated by Django 5.2.6 on 2026-04-23 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_unified_logs_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.agentconversation",
                verbose_name="生成会话",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="generation_metadata",
            field=models.JSONField(default=dict, verbose_name="生成元数据"),
        ),
        migrations.AddField(
            model_name="testcase",
            name="prd_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.knowledgedocument",
                verbose_name="关联PRD文档",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="quality_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="质量评分"),
        ),
        migrations.AddField(
            model_name="testcase",
            name="source",
            field=models.CharField(
                choices=[
                    ("chatbot", "Chatbot生成"),
                    ("manual_upload", "手动上传PRD"),
                    ("manual_create", "手动创建"),
                ],
                db_index=True,
                default="manual_create",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcases",
                to="core.module",
                verbose_name="所属模块",
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["project", "source"], name="core_test_c_project_1d775f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["prd_document"], name="core_test_c_prd_doc_536a24_idx"
            ),
        ),
    ]
