# Generated by Django 5.2.6 on 2026-04-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_source_fields_for_toolchain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="embedding",
        ),
    ]
