# Generated by Django 5.2.6 on 2026-05-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_knowledgedocument_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testflowexecution",
            name="test_flow",
        ),
        migrations.RemoveField(
            model_name="testflowexecution",
            name="user",
        ),
        migrations.RemoveField(
            model_name="testexecution",
            name="collection_execution",
        ),
        migrations.DeleteModel(
            name="TestFlow",
        ),
        migrations.DeleteModel(
            name="TestFlowExecution",
        ),
    ]
