# Generated by Django 5.2.6 on 2026-05-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_testflowexecution_test_flow_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="module",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="prd_document",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="project",
        ),
        migrations.RemoveField(
            model_name="testexecution",
            name="test_case",
        ),
    ]
