# Generated by Django 5.2.6 on 2026-05-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_testcase_conversation_and_more"),
        ("testmanager_app", "0009_alter_featuretestcase_expected_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="collection_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_executions",
                to="testmanager_app.collectionexecution",
                verbose_name="所属集合执行",
            ),
        ),
        migrations.DeleteModel(
            name="TestCase",
        ),
    ]
