# Generated by Django 5.2.6 on 2026-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_testexecution_collection_execution_delete_testcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentconversation",
            name="agent_type",
            field=models.CharField(
                choices=[("test_generation", "Test Generation Agent")],
                max_length=50,
                verbose_name="Agent Type",
            ),
        ),
        migrations.DeleteModel(
            name="AgentExecution",
        ),
    ]
