# Generated by Django 5.2.6 on 2025-12-12 09:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="测试标题")),
                ("pre_steps", models.TextField(blank=True, verbose_name="前置步骤")),
                ("steps", models.TextField(verbose_name="操作步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "actual_result",
                    models.TextField(blank=True, verbose_name="实际结果"),
                ),
                ("to_confirm", models.TextField(blank=True, verbose_name="待确定")),
                (
                    "is_passed",
                    models.BooleanField(blank=True, null=True, verbose_name="是否通过"),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=50, verbose_name="版本号"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "功能测试用例",
                "verbose_name_plural": "功能测试用例",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="角色名称")),
                (
                    "permission",
                    models.CharField(
                        choices=[("view", "仅查看"), ("crud", "增删改查")],
                        max_length=20,
                        verbose_name="权限类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="请求名称")),
                ("description", models.TextField(blank=True, verbose_name="请求描述")),
                ("url", models.URLField(verbose_name="请求URL")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("headers", models.TextField(blank=True, verbose_name="请求头")),
                ("body", models.TextField(blank=True, verbose_name="请求体")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_requests",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "API请求",
                "verbose_name_plural": "API请求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiAssertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assertion_type",
                    models.CharField(
                        choices=[
                            ("status_code", "状态码"),
                            ("response_time", "响应时间"),
                            ("response_body", "响应体"),
                            ("response_header", "响应头"),
                        ],
                        max_length=20,
                        verbose_name="断言类型",
                    ),
                ),
                (
                    "field",
                    models.CharField(blank=True, max_length=100, verbose_name="字段名"),
                ),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("equals", "等于"),
                            ("contains", "包含"),
                            ("not_contains", "不包含"),
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                        ],
                        max_length=20,
                        verbose_name="比较方式",
                    ),
                ),
                (
                    "expected_value",
                    models.CharField(max_length=200, verbose_name="期望值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="testmanager_app.apirequest",
                        verbose_name="API请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "API断言",
                "verbose_name_plural": "API断言",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                ("description", models.TextField(blank=True, verbose_name="模块描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "模块",
                "verbose_name_plural": "模块",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="RequestCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="集合名称")),
                ("description", models.TextField(blank=True, verbose_name="集合描述")),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("concurrent", "并发执行"),
                            ("sequential", "顺序执行"),
                            ("chain", "链式执行（支持变量传递）"),
                        ],
                        default="concurrent",
                        max_length=20,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_collections",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "请求集合",
                "verbose_name_plural": "请求集合",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="总请求数"),
                ),
                (
                    "passed_requests",
                    models.IntegerField(default=0, verbose_name="通过请求数"),
                ),
                (
                    "failed_requests",
                    models.IntegerField(default=0, verbose_name="失败请求数"),
                ),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testmanager_app.requestcollection",
                        verbose_name="请求集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "集合执行记录",
                "verbose_name_plural": "集合执行记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="用例标题")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "紧急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                ("steps", models.TextField(verbose_name="测试步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="testmanager_app.module",
                        verbose_name="所属模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[("testcase", "功能测试用例"), ("api", "API测试")],
                        default="testcase",
                        max_length=10,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("blocked", "阻塞"),
                            ("skipped", "跳过"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "actual_result",
                    models.TextField(blank=True, verbose_name="实际结果"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="备注")),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="执行时间",
                    ),
                ),
                (
                    "execution_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "api_response_data",
                    models.JSONField(blank=True, null=True, verbose_name="API响应数据"),
                ),
                ("api_logs", models.TextField(blank=True, verbose_name="API执行日志")),
                (
                    "api_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testmanager_app.apirequest",
                        verbose_name="API请求",
                    ),
                ),
                (
                    "collection_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_executions",
                        to="testmanager_app.collectionexecution",
                        verbose_name="所属集合执行",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testmanager_app.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试执行记录",
                "verbose_name_plural": "测试执行记录",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="报告名称")),
                ("description", models.TextField(blank=True, verbose_name="报告描述")),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                (
                    "total_cases",
                    models.IntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "passed_cases",
                    models.IntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "failed_cases",
                    models.IntegerField(default=0, verbose_name="失败用例数"),
                ),
                (
                    "blocked_cases",
                    models.IntegerField(default=0, verbose_name="阻塞用例数"),
                ),
                (
                    "skipped_cases",
                    models.IntegerField(default=0, verbose_name="跳过用例数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        max_length=10,
                        verbose_name="测试结果",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="响应时间(ms)"
                    ),
                ),
                ("response_body", models.TextField(blank=True, verbose_name="响应体")),
                (
                    "response_headers",
                    models.TextField(blank=True, verbose_name="响应头"),
                ),
                (
                    "assertion_results",
                    models.JSONField(blank=True, null=True, verbose_name="断言结果"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="testmanager_app.apirequest",
                        verbose_name="API请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "API测试结果",
                "verbose_name_plural": "API测试结果",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="TestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, verbose_name="脚本描述")),
                (
                    "script_type",
                    models.CharField(
                        choices=[("api", "API测试"), ("yaml", "YAML配置")],
                        default="api",
                        max_length=20,
                        verbose_name="脚本类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="YAML格式的API测试配置", verbose_name="脚本内容"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scripts",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试脚本",
                "verbose_name_plural": "测试脚本",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testmanager_app.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本执行记录",
                "verbose_name_plural": "脚本执行记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="执行顺序"
                    ),
                ),
                (
                    "stop_on_failure",
                    models.BooleanField(default=True, verbose_name="失败时停止"),
                ),
                (
                    "extract_rules",
                    models.JSONField(
                        blank=True,
                        help_text='JSON格式: [{"name": "var_name", "jsonpath": "$.data.id"}]',
                        null=True,
                        verbose_name="变量提取规则",
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(
                        default=1,
                        help_text="该请求在集合中的执行次数",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "请求次数必须大于0"
                            ),
                            django.core.validators.MaxValueValidator(
                                1000, "单次请求次数不能超过1000"
                            ),
                        ],
                        verbose_name="请求次数",
                    ),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_requests",
                        to="testmanager_app.apirequest",
                        verbose_name="API请求",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_requests",
                        to="testmanager_app.requestcollection",
                        verbose_name="请求集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "集合请求关联",
                "verbose_name_plural": "集合请求关联",
                "ordering": ["order_index"],
                "unique_together": {("collection", "api_request")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="testmanager_app.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色关联",
                "verbose_name_plural": "用户角色关联",
                "ordering": ["-created_at"],
                "unique_together": {("user", "role")},
            },
        ),
    ]
