# Generated by Django 5.2.6 on 2026-04-09 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="请求名称")),
                ("description", models.TextField(blank=True, verbose_name="请求描述")),
                ("url", models.URLField(verbose_name="请求URL")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("headers", models.TextField(blank=True, verbose_name="请求头")),
                ("body", models.TextField(blank=True, verbose_name="请求体")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="执行顺序"
                    ),
                ),
                (
                    "extract_rules",
                    models.JSONField(
                        blank=True,
                        help_text='JSON格式: [{"name": "var_name", "jsonpath": "$.data.id"}]',
                        null=True,
                        verbose_name="变量提取规则",
                    ),
                ),
                (
                    "stop_on_failure",
                    models.BooleanField(default=True, verbose_name="失败时停止"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="链式执行时，仅执行已启用的请求",
                        verbose_name="启用状态",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_requests",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "API请求",
                "verbose_name_plural": "API请求",
                "db_table": "api_request",
                "ordering": ["project", "order_index", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiAssertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assertion_type",
                    models.CharField(
                        choices=[
                            ("status_code", "状态码"),
                            ("response_time", "响应时间"),
                            ("response_body_field", "响应体字段"),
                            ("response_header_field", "响应头字段"),
                            ("jsonpath", "JSONPath断言"),
                        ],
                        max_length=30,
                        verbose_name="断言类型",
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="字段路径"
                    ),
                ),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("equals", "等于"),
                            ("contains", "包含"),
                            ("not_contains", "不包含"),
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                        ],
                        max_length=20,
                        verbose_name="比较方式",
                    ),
                ),
                (
                    "expected_value",
                    models.CharField(max_length=200, verbose_name="期望值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="testmanager_app.apirequest",
                        verbose_name="API请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "API断言",
                "verbose_name_plural": "API断言",
                "db_table": "api_assertion",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Token密钥"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Token值",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="最后使用时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "认证Token",
                "verbose_name_plural": "认证Token",
                "db_table": "auth_token",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="FeatureTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="测试标题")),
                ("pre_steps", models.TextField(blank=True, verbose_name="前置步骤")),
                ("steps", models.TextField(verbose_name="操作步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "actual_result",
                    models.TextField(blank=True, verbose_name="实际结果"),
                ),
                ("to_confirm", models.TextField(blank=True, verbose_name="待确定")),
                (
                    "is_passed",
                    models.BooleanField(blank=True, null=True, verbose_name="是否通过"),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=50, verbose_name="版本号"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_test_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_test_cases",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "功能测试用例",
                "verbose_name_plural": "功能测试用例",
                "db_table": "feature_test_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="集合名称")),
                ("description", models.TextField(blank=True, verbose_name="集合描述")),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("sequential", "顺序执行"),
                            ("concurrent", "并发执行"),
                            ("chain", "链式执行（支持变量传递）"),
                        ],
                        default="concurrent",
                        max_length=20,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_collections",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "请求集合",
                "verbose_name_plural": "请求集合",
                "db_table": "request_collection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="总请求数"),
                ),
                (
                    "passed_requests",
                    models.IntegerField(default=0, verbose_name="通过请求数"),
                ),
                (
                    "failed_requests",
                    models.IntegerField(default=0, verbose_name="失败请求数"),
                ),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_executions",
                        to="testmanager_app.requestcollection",
                        verbose_name="请求集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "集合执行记录",
                "verbose_name_plural": "集合执行记录",
                "db_table": "collection_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="报告名称")),
                ("description", models.TextField(blank=True, verbose_name="报告描述")),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                (
                    "total_cases",
                    models.IntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "passed_cases",
                    models.IntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "failed_cases",
                    models.IntegerField(default=0, verbose_name="失败用例数"),
                ),
                (
                    "blocked_cases",
                    models.IntegerField(default=0, verbose_name="阻塞用例数"),
                ),
                (
                    "skipped_cases",
                    models.IntegerField(default=0, verbose_name="跳过用例数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "db_table": "test_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, verbose_name="脚本描述")),
                (
                    "script_type",
                    models.CharField(
                        choices=[("api", "API测试"), ("yaml", "YAML配置")],
                        default="api",
                        max_length=20,
                        verbose_name="脚本类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="YAML格式的API测试配置", verbose_name="脚本内容"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scripts",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试脚本",
                "verbose_name_plural": "测试脚本",
                "db_table": "test_script",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="script_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_executions",
                        to="testmanager_app.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本执行记录",
                "verbose_name_plural": "脚本执行记录",
                "db_table": "script_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="执行顺序"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("normal", "正常请求"),
                            ("setup", "Setup前置请求"),
                            ("teardown", "Teardown后置请求"),
                        ],
                        default="normal",
                        help_text="Setup: 在正常请求前执行；Teardown: 在正常请求后执行（无论成功失败）",
                        max_length=20,
                        verbose_name="请求类型",
                    ),
                ),
                (
                    "stop_on_failure",
                    models.BooleanField(default=True, verbose_name="失败时停止"),
                ),
                (
                    "extract_rules",
                    models.JSONField(
                        blank=True,
                        help_text='JSON格式: [{"name": "var_name", "jsonpath": "$.data.id"}]',
                        null=True,
                        verbose_name="变量提取规则",
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(
                        default=1,
                        help_text="该请求在集合中的执行次数",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "请求次数必须大于0"
                            ),
                            django.core.validators.MaxValueValidator(
                                1000, "单次请求次数不能超过1000"
                            ),
                        ],
                        verbose_name="请求次数",
                    ),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_requests",
                        to="testmanager_app.apirequest",
                        verbose_name="API请求",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_requests",
                        to="testmanager_app.requestcollection",
                        verbose_name="请求集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "集合请求关联",
                "verbose_name_plural": "集合请求关联",
                "db_table": "collection_request",
                "ordering": ["order_index"],
                "unique_together": {("collection", "api_request")},
            },
        ),
    ]
