# Generated by Django 5.2.6 on 2025-12-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanager_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestcollection",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_collections",
                to="testmanager_app.project",
                verbose_name="所属项目",
            ),
        ),
    ]
