# Generated by Django 5.2.6 on 2026-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanager_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestcollection",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='格式: [{"key": "baseUrl", "value": "https://api.example.com"}]',
                verbose_name="场景变量",
            ),
        ),
    ]
