# Generated by Django 5.2.6 on 2026-04-15 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_chatbotexecutionlog"),
        ("testmanager_app", "0002_add_variables_to_requestcollection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PressureTestConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "pressure_mode",
                    models.CharField(
                        choices=[
                            ("instant", "瞬时并发"),
                            ("sustained", "持续并发"),
                            ("batch", "分批并发"),
                        ],
                        max_length=20,
                        verbose_name="压测模式",
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(
                        default=100,
                        help_text="瞬时并发模式：总请求数（最大1000）",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                        verbose_name="请求次数",
                    ),
                ),
                (
                    "rate_per_second",
                    models.IntegerField(
                        default=10,
                        help_text="持续并发模式：每秒发起的请求数",
                        verbose_name="每秒请求数",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=60,
                        help_text="持续并发模式：持续执行的秒数",
                        verbose_name="持续秒数",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=50,
                        help_text="分批并发模式：每批发起的请求数",
                        verbose_name="每批数量",
                    ),
                ),
                (
                    "batch_interval",
                    models.IntegerField(
                        default=5,
                        help_text="分批并发模式：批次之间的间隔（秒）",
                        verbose_name="批次间隔",
                    ),
                ),
                (
                    "max_concurrent",
                    models.IntegerField(
                        default=100,
                        help_text="同时最多发起的请求数（最大1000）",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                        verbose_name="最大并发数",
                    ),
                ),
                (
                    "monitor_server",
                    models.BooleanField(default=False, verbose_name="监控服务器"),
                ),
                (
                    "ssh_config",
                    models.JSONField(
                        blank=True,
                        help_text='JSON格式: {"host": "", "port": 22, "username": "", "password": ""}',
                        null=True,
                        verbose_name="SSH配置",
                    ),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pressure_test_configs",
                        to="testmanager_app.apirequest",
                        verbose_name="测试请求",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pressure_test_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pressure_test_configs",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "压测配置",
                "verbose_name_plural": "压测配置",
                "db_table": "pressure_test_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PressureTestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("stopped", "已停止"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行耗时（秒）"
                    ),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="总请求数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功数"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                (
                    "error_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="错误率（%）"
                    ),
                ),
                (
                    "min_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最小响应时间（ms）"
                    ),
                ),
                (
                    "max_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最大响应时间（ms）"
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="平均响应时间（ms）"
                    ),
                ),
                (
                    "p50_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P50响应时间（ms）"
                    ),
                ),
                (
                    "p90_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P90响应时间（ms）"
                    ),
                ),
                (
                    "p95_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P95响应时间（ms）"
                    ),
                ),
                (
                    "p99_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P99响应时间（ms）"
                    ),
                ),
                (
                    "throughput",
                    models.FloatField(
                        blank=True, null=True, verbose_name="吞吐量（RPS）"
                    ),
                ),
                (
                    "peak_concurrent",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="峰值并发数"
                    ),
                ),
                (
                    "server_metrics",
                    models.JSONField(
                        blank=True, null=True, verbose_name="服务器监控数据"
                    ),
                ),
                (
                    "raw_results",
                    models.JSONField(
                        blank=True,
                        help_text="每次请求的详细结果，用于后续分析",
                        null=True,
                        verbose_name="原始结果数据",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testmanager_app.pressuretestconfig",
                        verbose_name="压测配置",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pressure_test_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "压测执行记录",
                "verbose_name_plural": "压测执行记录",
                "db_table": "pressure_test_execution",
                "ordering": ["-started_at"],
            },
        ),
    ]
