# Generated by Django 5.2.6 on 2025-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanager_app", "0003_authtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiassertion",
            name="field",
        ),
        migrations.AddField(
            model_name="apiassertion",
            name="field_path",
            field=models.CharField(blank=True, max_length=200, verbose_name="字段路径"),
        ),
        migrations.AlterField(
            model_name="apiassertion",
            name="assertion_type",
            field=models.CharField(
                choices=[
                    ("status_code", "状态码"),
                    ("response_time", "响应时间"),
                    ("response_body_field", "响应体字段"),
                    ("response_header_field", "响应头字段"),
                ],
                max_length=30,
                verbose_name="断言类型",
            ),
        ),
    ]
