# Generated by Django 5.2.6 on 2026-04-15 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_chatbotexecutionlog"),
        ("testmanager_app", "0003_pressuretestconfig_pressuretestexecution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedPressureTestConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scenario",
                    models.JSONField(
                        help_text='JSON格式定义测试场景和步骤:\n        {\n            "scenario_name": "场景名称",\n            "steps": [\n                {\n                    "name": "步骤名称",\n                    "api_request_id": 1,\n                    "weight": 1,\n                    "extractors": [\n                        {"name": "token", "type": "json_path", "expression": "$.data.token"}\n                    ],\n                    "headers": {"Authorization": "Bearer ${token}"},\n                    "think_time": {"min": 1, "max": 3}\n                }\n            ]\n        }',
                        verbose_name="测试场景",
                    ),
                ),
                (
                    "host",
                    models.URLField(
                        help_text="压测目标的基础URL，例如: http://localhost:8080",
                        verbose_name="目标服务器地址",
                    ),
                ),
                (
                    "user_count",
                    models.IntegerField(
                        default=100,
                        help_text="同时模拟的用户数量",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="并发用户数",
                    ),
                ),
                (
                    "spawn_rate",
                    models.IntegerField(
                        default=10,
                        help_text="每秒启动的用户数",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="启动速率",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=60,
                        help_text="压测持续的最大秒数",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                        verbose_name="持续时间(秒)",
                    ),
                ),
                (
                    "use_distributed",
                    models.BooleanField(
                        default=False,
                        help_text="是否启用分布式Worker模式",
                        verbose_name="启用分布式",
                    ),
                ),
                (
                    "worker_count",
                    models.IntegerField(
                        default=1,
                        help_text="分布式模式下的Worker节点数量",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Worker数量",
                    ),
                ),
                (
                    "web_ui_port",
                    models.IntegerField(
                        default=18089,
                        help_text="Locust Web UI访问端口",
                        verbose_name="Web UI端口",
                    ),
                ),
                (
                    "enable_web_ui",
                    models.BooleanField(
                        default=True,
                        help_text="是否启动Locust原生Web界面",
                        verbose_name="启用Web UI",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="要运行的任务标签列表",
                        verbose_name="任务标签",
                    ),
                ),
                (
                    "exclude_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="要排除的任务标签列表",
                        verbose_name="排除标签",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advanced_pressure_test_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced_pressure_test_configs",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "高级压测配置",
                "verbose_name_plural": "高级压测配置",
                "db_table": "advanced_pressure_test_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvancedPressureTestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("stopped", "已停止"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行耗时(秒)"
                    ),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="总请求数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功数"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                (
                    "error_rate",
                    models.FloatField(blank=True, null=True, verbose_name="错误率(%)"),
                ),
                (
                    "min_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最小响应时间(ms)"
                    ),
                ),
                (
                    "max_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最大响应时间(ms)"
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="平均响应时间(ms)"
                    ),
                ),
                (
                    "p50_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P50响应时间(ms)"
                    ),
                ),
                (
                    "p90_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P90响应时间(ms)"
                    ),
                ),
                (
                    "p95_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P95响应时间(ms)"
                    ),
                ),
                (
                    "p99_response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="P99响应时间(ms)"
                    ),
                ),
                (
                    "throughput",
                    models.FloatField(
                        blank=True, null=True, verbose_name="吞吐量(RPS)"
                    ),
                ),
                (
                    "current_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="当前用户数"
                    ),
                ),
                (
                    "peak_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="峰值用户数"
                    ),
                ),
                (
                    "worker_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Worker数量"
                    ),
                ),
                (
                    "worker_status",
                    models.JSONField(
                        blank=True,
                        help_text="Worker节点状态信息",
                        null=True,
                        verbose_name="Worker状态",
                    ),
                ),
                (
                    "report_html",
                    models.TextField(
                        blank=True, null=True, verbose_name="HTML报告内容"
                    ),
                ),
                (
                    "raw_results",
                    models.JSONField(
                        blank=True,
                        help_text="每次请求的详细结果",
                        null=True,
                        verbose_name="原始结果数据",
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, null=True, verbose_name="错误日志"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="testmanager_app.advancedpressuretestconfig",
                        verbose_name="压测配置",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advanced_pressure_test_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "高级压测执行记录",
                "verbose_name_plural": "高级压测执行记录",
                "db_table": "advanced_pressure_test_execution",
                "ordering": ["-started_at"],
            },
        ),
    ]
