# Generated by Django 5.2.6 on 2025-12-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testmanager_app",
            "0004_remove_apiassertion_field_apiassertion_field_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("normal", "正常请求"),
                    ("setup", "Setup前置请求"),
                    ("teardown", "Teardown后置请求"),
                ],
                default="normal",
                help_text="Setup: 在正常请求前执行；Teardown: 在正常请求后执行（无论成功失败）",
                max_length=20,
                verbose_name="请求类型",
            ),
        ),
    ]
