# Generated by Django 5.2.6 on 2026-04-21 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanager_app", "0004_advancedpressuretestconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiassertion",
            name="is_critical",
            field=models.BooleanField(
                default=False,
                help_text="关键断言失败时整个测试标记为失败",
                verbose_name="是否关键断言",
            ),
        ),
        migrations.AlterField(
            model_name="pressuretestconfig",
            name="max_concurrent",
            field=models.IntegerField(
                default=100,
                help_text="同时最多发起的请求数（单机压测建议≤200，最大200）",
                validators=[django.core.validators.MaxValueValidator(200)],
                verbose_name="最大并发数",
            ),
        ),
    ]
