# Generated by Django 5.2.6 on 2026-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanager_app", "0005_add_is_critical_to_apiassertion"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancedpressuretestexecution",
            name="logs",
            field=models.TextField(
                blank=True,
                help_text="高级压测执行过程的完整日志",
                verbose_name="执行日志",
            ),
        ),
        migrations.AddField(
            model_name="pressuretestexecution",
            name="logs",
            field=models.TextField(
                blank=True, help_text="压测执行过程的完整日志", verbose_name="执行日志"
            ),
        ),
    ]
