# Generated by Django 5.2.6 on 2026-04-23 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_source_fields_for_toolchain"),
        ("testmanager_app", "0006_unified_logs_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testscript",
            name="source",
            field=models.CharField(
                choices=[
                    ("chatbot", "Chatbot生成"),
                    ("manual_upload", "手动上传"),
                    ("manual_create", "手动创建"),
                ],
                db_index=True,
                default="manual_create",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AddIndex(
            model_name="testscript",
            index=models.Index(
                fields=["project", "source"], name="test_script_project_a3e630_idx"
            ),
        ),
    ]
