# Generated by Django 5.2.6 on 2026-05-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_testflowexecution_test_flow_and_more"),
        ("testmanager_app", "0007_add_source_fields_for_toolchain"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="collectionrequest",
            name="api_request",
        ),
        migrations.RemoveField(
            model_name="collectionrequest",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="requestcollection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="requestcollection",
            name="project",
        ),
        migrations.DeleteModel(
            name="CollectionExecution",
        ),
        migrations.DeleteModel(
            name="CollectionRequest",
        ),
        migrations.DeleteModel(
            name="RequestCollection",
        ),
    ]
