"""
Django settings for testmanager project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
import os
import sys
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Force UTF-8 encoding for stdout/stderr on Windows to avoid GBK codec errors
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')  # type: ignore[union-attr]
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')  # type: ignore[union-attr]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in environment variables or .env file
_secret_key = os.getenv('SECRET_KEY')
if not _secret_key:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("SECRET_KEY environment variable is not set. Please set it in .env or environment variables.")
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'testserver,localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI服务器，需要放在最前面
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "channels",
    "testmanager_app",
    "test_ui_app",
    "core",  # 核心模块
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "testmanager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# 部署配置
# 已统一使用 ASGI 模式部署，通过 Daphne 服务器运行
# WSGI 配置仅作为备用（用于某些特殊情况如 django-admin 命令）
WSGI_APPLICATION = "testmanager.wsgi.application"
ASGI_APPLICATION = "testmanager.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
# Database configuration with proper handling for empty password
db_config = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': os.getenv('DB_NAME', 'mydjangodb'),
    'USER': os.getenv('DB_USER', 'root'),
    'HOST': os.getenv('DB_HOST', '172.17.61.120'),
    'PORT': os.getenv('DB_PORT', '3306'),
}

# Only set PASSWORD if it's explicitly provided and not empty
db_password = os.getenv('DB_PASSWORD', '').strip()
if db_password:
    db_config['PASSWORD'] = db_password

db_config['CONN_MAX_AGE'] = 60  # type: ignore[assignment]

DATABASES = {
    'default': db_config
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (User uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',')
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        # 使用自定义的Token认证，支持过期时间
        'testmanager_app.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 全局权限默认需要认证
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '20/minute',
    },
}

# Cache configuration - Redis
REDIS_HOST = os.getenv('REDIS_HOST', '172.17.61.120')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_DB = os.getenv('REDIS_DB', '1')
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,  # 连接超时5秒
            "SOCKET_TIMEOUT": 5,  # 操作超时5秒（降低避免长时间阻塞）
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "socket_connect_timeout": 5,
                "socket_timeout": 5,
                "socket_keepalive": True,  # 启用TCP keepalive
                "socket_keepalive_options": {
                    1: 1,  # TCP_KEEPIDLE: 1秒后开始发送keepalive探测
                    2: 1,  # TCP_KEEPINTVL: 探测间隔1秒
                    3: 3,  # TCP_KEEPCNT: 最多3次探测
                } if os.name != 'nt' else {},  # Windows不支持这些选项
                "retry_on_timeout": True,  # 超时时自动重试
                "health_check_interval": 30,  # 每30秒检查连接健康状态
            },
            # django-redis会自动管理连接池，不需要手动指定连接池类
            "IGNORE_EXCEPTIONS": True,  # 改为True，避免Redis问题导致整个请求失败
        }
    }
}

# 可选：会话也进 Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Celery配置 - 使用单独的Redis数据库(DB 2)避免与cache和channels冲突
CELERY_REDIS_DB = os.getenv('CELERY_REDIS_DB', '2')
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{CELERY_REDIS_DB}"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{CELERY_REDIS_DB}"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30分钟超时
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25分钟软超时
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
# Celery broker连接配置
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Channels配置 - 使用单独的Redis数据库(DB 3)避免与cache和celery冲突
# 注意：生产环境应该使用Redis，开发环境如果Redis不可用，可以使用内存通道层
# 内存通道层限制：只能用于单进程部署，不能用于多进程/多服务器场景
USE_REDIS_CHANNELS = os.getenv('USE_REDIS_CHANNELS', 'true').lower() == 'true'
CHANNELS_REDIS_DB = os.getenv('CHANNELS_REDIS_DB', '3')

if USE_REDIS_CHANNELS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/{CHANNELS_REDIS_DB}"],
                "capacity": 1500,  # 默认通道容量
                "expiry": 10,  # 消息过期时间（秒）
                # 注意：channels_redis 的慢任务警告阈值在库内部硬编码（约0.1秒）
                # 无法通过配置项修改，如果需要调整，请使用日志配置过滤警告
            },
        },
    }
else:
    # 使用内存通道层（仅限开发环境，单进程）
    # 设置环境变量 USE_REDIS_CHANNELS=false 以使用内存通道层
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        'console_utf8': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
    },
    'root': {
        'handlers': ['console_utf8'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console_utf8'],
            'level': 'INFO',
            'propagate': False,
        },
        'test_ui_app': {
            'handlers': ['console_utf8'],
            'level': 'INFO',
            'propagate': False,
        },
        'testmanager_app': {
            'handlers': ['console_utf8'],
            'level': 'INFO',
            'propagate': False,
        },
        'channels_redis': {
            'handlers': ['console_utf8'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Windows UTF-8 控制台支持
import sys
import io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')


# ═══════════════════════════════════════════════════════════════════
# 意图分类配置
# ═══════════════════════════════════════════════════════════════════

INTENT_CONFIG = {
    # LLM fallback 触发阈值：消息长度超过此值且规则返回 CHAT 时触发 LLM
    "LLM_FALLBACK_MESSAGE_LEN": int(os.getenv("INTENT_LLM_FALLBACK_LEN", "10")),
    
    # 置信度阈值：score 低于此值时触发 LLM fallback
    "CONFIDENCE_THRESHOLD": float(os.getenv("INTENT_CONFIDENCE_THRESHOLD", "0.6")),
    
    # 缓存配置
    "CACHE_ENABLED": os.getenv("INTENT_CACHE_ENABLED", "true").lower() == "true",
    "CACHE_TTL": int(os.getenv("INTENT_CACHE_TTL", "300")),
}

# ═══════════════════════════════════════════════════════════════════
# 上下文存储配置
# ═══════════════════════════════════════════════════════════════════

CONTEXT_ROOT_DIR = Path(os.getenv("CONTEXT_ROOT_DIR", str(BASE_DIR / "context_data")))

# ═══════════════════════════════════════════════════════════════════
# HTTPS 安全头配置（仅生产环境）
# ═══════════════════════════════════════════════════════════════════

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# MCP Server 配置
MCP_SERVERS = {
    "playwright": {
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@playwright/mcp@latest"],
        "auto_reconnect": True,
        "health_check_interval": 60,
        "max_reconnect_attempts": 3,
        "reconnect_delay": 5,
    },
    "skill-manager": {  # 新增: Skill 管理 MCP Server
        "transport": "stdio",
        "command": "python",
        "args": ["-m", "skills.mcp-skill-manager.main"],
        "env": {
            "PYTHONIOENCODING": "utf-8",
            "PYTHONUTF8": "1"
        },
        "auto_reconnect": True,
        "health_check_interval": 60,
        "max_reconnect_attempts": 3,
        "reconnect_delay": 5,
    },
}