# Generated by Django 5.2.6 on 2026-01-05 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testmanager_app", "0005_collectionrequest_request_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementLocator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="定位器名称")),
                (
                    "locator_type",
                    models.CharField(
                        choices=[
                            ("id", "ID"),
                            ("name", "Name"),
                            ("css", "CSS选择器"),
                            ("xpath", "XPath"),
                            ("text", "文本内容"),
                            ("testid", "Test ID"),
                            ("role", "Role"),
                            ("label", "Label"),
                        ],
                        max_length=20,
                        verbose_name="定位器类型",
                    ),
                ),
                ("locator_value", models.TextField(verbose_name="定位器值")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "元素定位器",
                "verbose_name_plural": "元素定位器",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UITestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "browser_type",
                    models.CharField(
                        choices=[
                            ("chromium", "Chromium"),
                            ("firefox", "Firefox"),
                            ("webkit", "WebKit"),
                        ],
                        default="chromium",
                        max_length=20,
                        verbose_name="浏览器类型",
                    ),
                ),
                (
                    "headless",
                    models.BooleanField(default=True, verbose_name="无头模式"),
                ),
                (
                    "viewport_width",
                    models.IntegerField(default=1280, verbose_name="视口宽度"),
                ),
                (
                    "viewport_height",
                    models.IntegerField(default=720, verbose_name="视口高度"),
                ),
                (
                    "timeout",
                    models.IntegerField(default=30000, verbose_name="超时时间(毫秒)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ui_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_test_scripts",
                        to="testmanager_app.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试脚本",
                "verbose_name_plural": "UI测试脚本",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UITestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(default=dict, verbose_name="结果摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "screenshots",
                    models.JSONField(default=list, verbose_name="截图列表"),
                ),
                (
                    "execution_log",
                    models.TextField(blank=True, verbose_name="执行日志"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ui_test_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="test_ui_app.uitestscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试执行记录",
                "verbose_name_plural": "UI测试执行记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UITestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("navigate", "导航"),
                            ("click", "点击"),
                            ("fill", "填写"),
                            ("select", "选择"),
                            ("hover", "悬停"),
                            ("wait", "等待"),
                            ("screenshot", "截图"),
                            ("assert", "断言"),
                            ("extract", "提取"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "action_params",
                    models.JSONField(default=dict, verbose_name="操作参数"),
                ),
                ("description", models.TextField(blank=True, verbose_name="步骤描述")),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "element_locator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steps",
                        to="test_ui_app.elementlocator",
                        verbose_name="元素定位器",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="test_ui_app.uitestscript",
                        verbose_name="所属脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试步骤",
                "verbose_name_plural": "UI测试步骤",
                "ordering": ["script", "step_order"],
                "unique_together": {("script", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="UITestStepExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(default=dict, verbose_name="结果数据"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "screenshot",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="截图路径"
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="test_ui_app.uitestexecution",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="test_ui_app.uiteststep",
                        verbose_name="测试步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试步骤执行记录",
                "verbose_name_plural": "UI测试步骤执行记录",
                "ordering": ["execution", "step__step_order"],
            },
        ),
    ]
