# Generated by Django 5.2.6 on 2026-04-09 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UITestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("actions", models.JSONField(default=list, verbose_name="动作列表")),
                (
                    "browser_type",
                    models.CharField(
                        choices=[
                            ("chromium", "Chromium"),
                            ("firefox", "Firefox"),
                            ("webkit", "WebKit"),
                        ],
                        default="chromium",
                        max_length=20,
                        verbose_name="浏览器类型",
                    ),
                ),
                (
                    "headless",
                    models.BooleanField(default=True, verbose_name="无头模式"),
                ),
                (
                    "viewport_width",
                    models.IntegerField(default=1280, verbose_name="视口宽度"),
                ),
                (
                    "viewport_height",
                    models.IntegerField(default=720, verbose_name="视口高度"),
                ),
                (
                    "timeout",
                    models.IntegerField(default=30000, verbose_name="超时时间(毫秒)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ui_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_test_scripts",
                        to="core.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试脚本",
                "verbose_name_plural": "UI测试脚本",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UITestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(default=dict, verbose_name="结果摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "screenshots",
                    models.JSONField(default=list, verbose_name="截图列表"),
                ),
                (
                    "execution_log",
                    models.TextField(blank=True, verbose_name="执行日志"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ui_test_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="test_ui_app.uitestscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试执行记录",
                "verbose_name_plural": "UI测试执行记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
