# Generated by Django 5.2.6 on 2026-01-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_ui_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uitestexecution",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
        migrations.AlterField(
            model_name="uiteststepexecution",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
    ]
