# Generated by Django 5.2.6 on 2026-01-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_ui_app", "0002_allow_null_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="uitestscript",
            name="script_code",
            field=models.TextField(blank=True, verbose_name="脚本代码"),
        ),
        migrations.AddField(
            model_name="uitestscript",
            name="script_type",
            field=models.CharField(
                choices=[("code", "代码模式"), ("steps", "步骤模式")],
                default="steps",
                max_length=20,
                verbose_name="脚本类型",
            ),
        ),
    ]
