# Generated by Django 5.2.6 on 2025-09-13 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                ("description", models.TextField(blank=True, verbose_name="模块描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="tests.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "模块",
                "verbose_name_plural": "模块",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="用例标题")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "紧急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                ("steps", models.TextField(verbose_name="测试步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="tests.module",
                        verbose_name="所属模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="tests.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("blocked", "阻塞"),
                            ("skipped", "跳过"),
                        ],
                        max_length=10,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "actual_result",
                    models.TextField(blank=True, verbose_name="实际结果"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="备注")),
                (
                    "executed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="执行时间"
                    ),
                ),
                (
                    "execution_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tests.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试执行记录",
                "verbose_name_plural": "测试执行记录",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="报告名称")),
                ("description", models.TextField(blank=True, verbose_name="报告描述")),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                (
                    "total_cases",
                    models.IntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "passed_cases",
                    models.IntegerField(default=0, verbose_name="通过用例数"),
                ),
                (
                    "failed_cases",
                    models.IntegerField(default=0, verbose_name="失败用例数"),
                ),
                (
                    "blocked_cases",
                    models.IntegerField(default=0, verbose_name="阻塞用例数"),
                ),
                (
                    "skipped_cases",
                    models.IntegerField(default=0, verbose_name="跳过用例数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="tests.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "ordering": ["-created_at"],
            },
        ),
    ]
