# Generated by Django 5.2.6 on 2025-09-13 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="请求名称")),
                ("description", models.TextField(blank=True, verbose_name="请求描述")),
                ("url", models.URLField(verbose_name="请求URL")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("headers", models.TextField(blank=True, verbose_name="请求头")),
                ("body", models.TextField(blank=True, verbose_name="请求体")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_requests",
                        to="tests.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "API请求",
                "verbose_name_plural": "API请求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiAssertion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assertion_type",
                    models.CharField(
                        choices=[
                            ("status_code", "状态码"),
                            ("response_time", "响应时间"),
                            ("response_body", "响应体"),
                            ("response_header", "响应头"),
                        ],
                        max_length=20,
                        verbose_name="断言类型",
                    ),
                ),
                (
                    "field",
                    models.CharField(blank=True, max_length=100, verbose_name="字段名"),
                ),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("equals", "等于"),
                            ("contains", "包含"),
                            ("not_contains", "不包含"),
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                        ],
                        max_length=20,
                        verbose_name="比较方式",
                    ),
                ),
                (
                    "expected_value",
                    models.CharField(max_length=200, verbose_name="期望值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "api_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="tests.apirequest",
                        verbose_name="API请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "API断言",
                "verbose_name_plural": "API断言",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="集合名称")),
                ("description", models.TextField(blank=True, verbose_name="集合描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_collections",
                        to="tests.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "requests",
                    models.ManyToManyField(
                        blank=True, to="tests.apirequest", verbose_name="API请求"
                    ),
                ),
            ],
            options={
                "verbose_name": "请求集合",
                "verbose_name_plural": "请求集合",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "total_requests",
                    models.IntegerField(default=0, verbose_name="总请求数"),
                ),
                (
                    "passed_requests",
                    models.IntegerField(default=0, verbose_name="通过请求数"),
                ),
                (
                    "failed_requests",
                    models.IntegerField(default=0, verbose_name="失败请求数"),
                ),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tests.requestcollection",
                        verbose_name="请求集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "集合执行记录",
                "verbose_name_plural": "集合执行记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, verbose_name="脚本描述")),
                (
                    "script_type",
                    models.CharField(
                        choices=[
                            ("python", "Python脚本"),
                            ("api", "API测试"),
                            ("selenium", "Selenium测试"),
                        ],
                        default="python",
                        max_length=20,
                        verbose_name="脚本类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="test_scripts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["py", "json", "txt"]
                            )
                        ],
                        verbose_name="脚本文件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scripts",
                        to="tests.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试脚本",
                "verbose_name_plural": "测试脚本",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tests.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本执行记录",
                "verbose_name_plural": "脚本执行记录",
                "ordering": ["-started_at"],
            },
        ),
    ]
